import Head from 'next/head';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CurrencyValidator from '@/components/CurrencyValidator';

import { fetchData } from '@/gateway/gateway';
import { useState } from 'react';
import { createDate } from '@/common/helpers';

export default function Home() {
  return (
    <>
      <Head>
        <title>currency validator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen">
        <Header />
        <CurrencyValidator />
        <Footer />
      </main>
    </>
  );
}

// import React, { useState, useEffect } from 'react';
// import axios from 'axios';

// const Converter = () => {
//   const [rates, setRates] = useState({});
//   const [amount, setAmount] = useState(0);
//   const [fromCurrency, setFromCurrency] = useState('USD');
//   const [toCurrency, setToCurrency] = useState('EUR');
//   const [result, setResult] = useState(0);

//   useEffect(() => {
//     const fetchRates = async () => {
//       const response = await axios.get(`https://api.exchangeratesapi.io/latest?base=${fromCurrency}`);
//       setRates(response.data.rates);
//     };
//     fetchRates();
//   }, [fromCurrency]);

//   const handleAmountChange = (event) => {
//     setAmount(event.target.value);
//   };

//   const handleFromCurrencyChange = (event) => {
//     setFromCurrency(event.target.value);
//   };

//   const handleToCurrencyChange = (event) => {
//     setToCurrency(event.target.value);
//   };

//   const handleSubmit = (event) => {
//     event.preventDefault();
//     const convertedAmount = amount / rates[toCurrency];
//     setResult(convertedAmount.toFixed(2));
//   };

//   return (
//     <div>
//       <h2>Currency Converter</h2>
//       <form onSubmit={handleSubmit}>
//         <div>
//           <label htmlFor="amount">Amount:</label>
//           <input type="number" id="amount" value={amount} onChange={handleAmountChange} />
//         </div>
//         <div>
//           <label htmlFor="fromCurrency">From Currency:</label>
//           <select id="fromCurrency" value={fromCurrency} onChange={handleFromCurrencyChange}>
//             <option value="USD">USD</option>
//             <option value="EUR">EUR</option>
//             <option value="GBP">GBP</option>
//             <option value="JPY">JPY</option>
//           </select>
//         </div>
//         <div>
//           <label htmlFor="toCurrency">To Currency:</label>
//           <select id="toCurrency" value={toCurrency} onChange={handleToCurrencyChange}>
//             <option value="USD">USD</option>
//             <option value="EUR">EUR</option>
//             <option value="GBP">GBP</option>
//             <option value="JPY">JPY</option>
//           </select>
//         </div>
//         <button type="submit">Convert</button>
//       </form>
//       <h3>{result}</h3>
//     </div>
//   );
// };

// export default Converter;
